# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20161223_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_directors',
            field=models.ManyToManyField(blank=True, to='members.Member'),
        ),
        migrations.AlterField(
            model_name='race',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsors', to='sponsors.Sponsor'),
        ),
    ]
